const DATA = [
  {name:"GitHub Student Developer Pack",price:"Gratis",cat:"dev",util:"Alta",via:"GitHub Education",time:"Anual",nota:"Paraguas de decenas de beneficios",url:"https://education.github.com/pack",logo:"github.com",
   desc:"Acceso a más de 100 herramientas y servicios gratuitos o con descuento para estudiantes. Incluye dominios, hosting, IDEs, bases de datos, seguridad, monitorización, cursos y mucho más. Es el punto de entrada para activar Copilot, DigitalOcean, Namecheap, Heroku, MongoDB, GitKraken, Educative y otros. Requiere verificación académica con correo universitario o documentación.",
   en:{nota:"Umbrella for dozens of benefits",via:"GitHub Education",time:"Annual",
       desc:"Access to over 100 free or discounted tools and services for students. Includes domains, hosting, IDEs, databases, security, monitoring, courses and much more. It is the entry point to activate Copilot, DigitalOcean, Namecheap, Heroku, MongoDB, GitKraken, Educative and others. Requires academic verification with a university email or documentation."}},

  {name:"GitHub Copilot",price:"Gratis",cat:"dev",util:"Alta",via:"GitHub Student Pack",time:"Mientras estudias",nota:"IA para código, imprescindible",url:"https://github.com/features/copilot/plans",logo:"github.com",
   desc:"Asistente de programación basado en IA que sugiere líneas y bloques de código en tiempo real dentro del editor. Compatible con VS Code, JetBrains, Neovim y otros. Soporta Python, JavaScript, TypeScript, Java, C++, Go, Rust y más. Incluye chat integrado para explicar código, detectar bugs, generar tests y documentar funciones. Imprescindible para acelerar el desarrollo.",
   en:{nota:"AI for code, essential",via:"GitHub Student Pack",time:"While studying",
       desc:"AI-powered programming assistant that suggests lines and code blocks in real time inside the editor. Compatible with VS Code, JetBrains, Neovim and others. Supports Python, JavaScript, TypeScript, Java, C++, Go, Rust and more. Includes integrated chat to explain code, detect bugs, generate tests and document functions. Essential for accelerating development."}},

  {name:"JetBrains IDEs (todos)",price:"Gratis",cat:"dev",util:"Alta",via:"JetBrains Education",time:"Anual renovable",nota:"IntelliJ, PyCharm, WebStorm…",url:"https://www.jetbrains.com/community/education/",logo:"jetbrains.com",
   desc:"Licencia para todos los IDEs de JetBrains: IntelliJ IDEA (Java/Kotlin), PyCharm (Python), WebStorm (JS/TS), PhpStorm, CLion (C/C++), DataGrip (SQL), GoLand, Rider (.NET), RubyMine, AppCode. Incluye refactoring inteligente, depurador avanzado, integración con Git, soporte de frameworks y análisis estático de código. Los más usados en entornos profesionales.",
   en:{name:"JetBrains IDEs (all)",nota:"IntelliJ, PyCharm, WebStorm…",via:"JetBrains Education",time:"Annual renewable",
       desc:"License for all JetBrains IDEs: IntelliJ IDEA (Java/Kotlin), PyCharm (Python), WebStorm (JS/TS), PhpStorm, CLion (C/C++), DataGrip (SQL), GoLand, Rider (.NET), RubyMine, AppCode. Includes smart refactoring, advanced debugger, Git integration, framework support and static code analysis. The most used in professional environments."}},

  {name:"Cursor Pro",price:"Gratis",cat:"dev",util:"Alta",via:"Cursor Education",time:"1 año",nota:"Editor IA, alternativa a Copilot",url:"https://www.cursor.com/students",logo:"cursor.com",
   desc:"Editor de código construido sobre VS Code con IA integrada en el núcleo. Permite editar con lenguaje natural, hacer refactors en múltiples archivos a la vez, chatear con el codebase completo y aplicar cambios con un solo clic. Compatible con todos los plugins de VS Code. Usa modelos como Claude y GPT-4. Especialmente potente para refactors grandes y comprensión de proyectos complejos.",
   en:{nota:"AI editor, Copilot alternative",via:"Cursor Education",time:"1 year",
       desc:"Code editor built on VS Code with AI integrated at its core. Allows editing with natural language, refactoring across multiple files at once, chatting with the entire codebase and applying changes with a single click. Compatible with all VS Code plugins. Uses models like Claude and GPT-4. Especially powerful for large refactors and understanding complex projects."}},

  {name:"GitKraken Student Pack",price:"Gratis",cat:"dev",util:"Media",via:"GitHub Student Pack",time:"Mientras estudias",nota:"GUI avanzado para Git",url:"https://www.gitkraken.com/github-student-developer-pack-bundle",logo:"gitkraken.com",
   desc:"Cliente gráfico para Git con visualización de ramas tipo árbol, resolución de conflictos integrada, historial visual de commits, integración con GitHub/GitLab/Bitbucket y gestión de pull requests sin salir del cliente. Incluye GitLens para VS Code. Útil para equipos y proyectos con ramas complejas o para quienes prefieren no usar la terminal para operaciones Git.",
   en:{nota:"Advanced GUI for Git",via:"GitHub Student Pack",time:"While studying",
       desc:"Graphical Git client with tree-style branch visualization, integrated conflict resolution, visual commit history, GitHub/GitLab/Bitbucket integration and pull request management without leaving the client. Includes GitLens for VS Code. Useful for teams and projects with complex branches or those who prefer not to use the terminal for Git operations."}},

  {name:"Replit Pro",price:"Descuento",cat:"dev",util:"Media",via:"Replit directo",time:"Mientras estudias",nota:"IDE online con descuento estudiante",url:"https://replit.com/pricing",logo:"replit.com",
   desc:"Entorno de desarrollo en la nube que permite programar desde el navegador sin instalar nada. Soporta más de 50 lenguajes. Incluye servidor integrado, base de datos clave-valor, despliegue automático, multiplayer para colaborar en tiempo real y IA asistente. Replit abandonó el GitHub Student Pack en diciembre de 2023; ahora ofrece descuento propio verificando con email universitario.",
   en:{nota:"Online IDE with student discount",via:"Replit direct",time:"While studying",
       desc:"Cloud development environment that lets you code from the browser without installing anything. Supports over 50 languages. Includes integrated server, key-value database, automatic deployment, multiplayer for real-time collaboration and AI assistant. Replit left the GitHub Student Pack in December 2023; now offers its own discount with university email verification."}},

  {name:"Unity Student",price:"Gratis",cat:"dev",util:"Media",via:"Unity Education",time:"Mientras estudias",nota:"Motor de juegos, plan Personal",url:"https://unity.com/products/unity-student",logo:"unity.com",
   desc:"Motor de juegos multiplataforma para crear experiencias 2D, 3D, VR y AR. Usado profesionalmente para videojuegos, simulaciones, visualizaciones arquitectónicas y aplicaciones interactivas. Incluye Unity Editor completo, Unity Asset Store, cursos en Unity Learn, acceso a plantillas de proyectos y capacidad de publicar en iOS, Android, PC, consolas y web. Lenguaje principal: C#.",
   en:{nota:"Game engine, Personal plan",via:"Unity Education",time:"While studying",
       desc:"Cross-platform game engine for creating 2D, 3D, VR and AR experiences. Used professionally for video games, simulations, architectural visualizations and interactive applications. Includes full Unity Editor, Unity Asset Store, Unity Learn courses, access to project templates and the ability to publish on iOS, Android, PC, consoles and web. Main language: C#."}},

  {name:"Frontend Masters",price:"Gratis",cat:"edu",util:"Alta",via:"GitHub Student Pack",time:"6 meses",nota:"Cursos avanzados de frontend",url:"https://frontendmasters.com/welcome/github-student-developers/",logo:"frontendmasters.com",
   desc:"Plataforma de cursos técnicos avanzados impartidos por expertos de la industria. Especializada en frontend pero cubre también backend, DevOps y CS. Cursos destacados de JavaScript profundo, TypeScript, React, Vue, CSS avanzado, Node.js, algoritmos y estructuras de datos, rendimiento web, testing y arquitectura de aplicaciones. Muy valorada por desarrolladores senior y en procesos de selección.",
   en:{nota:"Advanced frontend courses",via:"GitHub Student Pack",time:"6 months",
       desc:"Advanced technical courses platform taught by industry experts. Specializes in frontend but also covers backend, DevOps and CS. Featured courses on deep JavaScript, TypeScript, React, Vue, advanced CSS, Node.js, algorithms and data structures, web performance, testing and application architecture. Highly valued by senior developers and in hiring processes."}},

  {name:"Educative",price:"Gratis",cat:"edu",util:"Alta",via:"GitHub Student Pack",time:"6 meses",nota:"Cursos interactivos de programación",url:"https://www.educative.io/github-students",logo:"educative.io",
   desc:"Plataforma de aprendizaje con cursos interactivos en el navegador sin necesidad de instalar nada. Especialmente fuerte en preparación para entrevistas técnicas (Grokking the Coding Interview, System Design). Cubre Python, Java, JavaScript, C++, Go, Rust, machine learning, cloud y DevOps. Los cursos incluyen ejercicios ejecutables, cuestionarios y proyectos guiados.",
   en:{nota:"Interactive programming courses",via:"GitHub Student Pack",time:"6 months",
       desc:"Learning platform with interactive browser-based courses with nothing to install. Especially strong for technical interview preparation (Grokking the Coding Interview, System Design). Covers Python, Java, JavaScript, C++, Go, Rust, machine learning, cloud and DevOps. Courses include executable exercises, quizzes and guided projects."}},

  {name:"Coursera Financial Aid",price:"Gratis",cat:"edu",util:"Alta",via:"Coursera directo",time:"Por curso",nota:"Solicitar beca por curso individual",url:"https://www.coursera.org/financial-aid",logo:"coursera.org",
   desc:"Ayuda económica para acceder a cursos y especializaciones de universidades como Stanford, Google, IBM, Meta o Johns Hopkins. Se solicita por curso explicando la situación económica. Aprobación en 2 semanas aproximadamente. Permite obtener certificados oficiales de forma gratuita. Útil para especializaciones de IA, ciencia de datos, marketing digital, programación y negocios.",
   en:{nota:"Apply for scholarship per course",via:"Coursera direct",time:"Per course",
       desc:"Financial aid to access courses and specializations from universities like Stanford, Google, IBM, Meta or Johns Hopkins. Applied per course by explaining your financial situation. Approval in approximately 2 weeks. Allows obtaining official certificates for free. Useful for AI, data science, digital marketing, programming and business specializations."}},

  {name:"edX Audit",price:"Gratis",cat:"edu",util:"Alta",via:"edX directo",time:"Permanente",nota:"Auditar cursos sin certificado",url:"https://www.edx.org",logo:"edx.org",
   desc:"Acceso gratuito al contenido de cursos de MIT, Harvard, Berkeley, Microsoft y otras instituciones en modo auditoría. Incluye vídeos, lecturas y ejercicios pero sin certificado ni calificaciones evaluadas. Ideal para aprender a tu ritmo sin coste. Cubre desde programación y ciencias de la computación hasta filosofía, economía e ingeniería. El certificado verificado tiene coste adicional.",
   en:{nota:"Audit courses without certificate",via:"edX direct",time:"Permanent",
       desc:"Free access to course content from MIT, Harvard, Berkeley, Microsoft and other institutions in audit mode. Includes videos, readings and exercises but without a certificate or graded assessments. Ideal for learning at your own pace at no cost. Covers everything from programming and computer science to philosophy, economics and engineering. Verified certificate has an additional cost."}},

  {name:"Microsoft Learn",price:"Gratis",cat:"edu",util:"Alta",via:"Microsoft directo",time:"Permanente",nota:"Retos + créditos para exámenes",url:"https://learn.microsoft.com/es-es/training/student-hub/",logo:"microsoft.com",
   desc:"Plataforma de aprendizaje oficial de Microsoft con módulos gratuitos sobre Azure, Microsoft 365, Power Platform, GitHub, Dynamics y más. Incluye rutas de aprendizaje estructuradas, laboratorios interactivos en sandbox y preparación para certificaciones oficiales como AZ-900, AZ-104, DP-900 o SC-900. Los desafíos estudiantiles pueden dar créditos de examen gratuitos.",
   en:{nota:"Challenges + exam credits",via:"Microsoft direct",time:"Permanent",
       desc:"Microsoft's official learning platform with free modules on Azure, Microsoft 365, Power Platform, GitHub, Dynamics and more. Includes structured learning paths, interactive sandbox labs and preparation for official certifications like AZ-900, AZ-104, DP-900 or SC-900. Student challenges can provide free exam credits."}},

  {name:"DigitalOcean",price:"Saldo gratuito",cat:"cloud",util:"Alta",via:"GitHub Student Pack",time:"1 vez",nota:"$200 créditos para VPS/cloud",url:"https://www.digitalocean.com/github-students",logo:"digitalocean.com",
   desc:"$200 en créditos para usar en Droplets (VPS), Kubernetes, bases de datos gestionadas (PostgreSQL, MySQL, Redis, MongoDB), App Platform, Spaces (object storage) y funciones serverless. Ideal para desplegar proyectos reales, prácticas de DevOps, aprender Kubernetes o alojar APIs y aplicaciones web. Interfaz sencilla y documentación excelente para empezar con cloud.",
   en:{nota:"$200 credits for VPS/cloud",via:"GitHub Student Pack",time:"One time",
       desc:"$200 in credits to use on Droplets (VPS), Kubernetes, managed databases (PostgreSQL, MySQL, Redis, MongoDB), App Platform, Spaces (object storage) and serverless functions. Ideal for deploying real projects, DevOps practice, learning Kubernetes or hosting APIs and web applications. Simple interface and excellent documentation to get started with cloud."}},

  {name:"AWS Educate",price:"Saldo gratuito",cat:"cloud",util:"Alta",via:"AWS directo",time:"Anual",nota:"Créditos + labs + badges oficiales",url:"https://aws.amazon.com/es/education/awseducate/",logo:"aws.amazon.com",
   desc:"Programa educativo de Amazon Web Services con créditos gratuitos, laboratorios guiados, rutas de aprendizaje y badges verificables. Cubre EC2, S3, Lambda, RDS, DynamoDB, SageMaker, CloudFormation y más. Incluye acceso a AWS Builder Labs para practicar sin coste real. Los badges de AWS Educate son reconocidos en LinkedIn y procesos de selección. No requiere tarjeta de crédito.",
   en:{nota:"Credits + labs + official badges",via:"AWS direct",time:"Annual",
       desc:"Amazon Web Services educational program with free credits, guided labs, learning paths and verifiable badges. Covers EC2, S3, Lambda, RDS, DynamoDB, SageMaker, CloudFormation and more. Includes access to AWS Builder Labs to practice at no real cost. AWS Educate badges are recognized on LinkedIn and in hiring processes. No credit card required."}},

  {name:"Google Cloud",price:"Saldo gratuito",cat:"cloud",util:"Alta",via:"Google for Education",time:"Anual",nota:"Créditos educativos variables",url:"https://cloud.google.com/edu/students",logo:"cloud.google.com",
   desc:"Créditos para Google Cloud Platform: Compute Engine, Cloud Storage, BigQuery, Cloud Run, Kubernetes Engine, Cloud Functions y APIs de IA como Vertex AI o Vision API. Ideal para proyectos de machine learning, análisis de datos a gran escala o aprender arquitecturas cloud nativas. Acceso a Qwiklabs para laboratorios prácticos y Google Cloud Skills Boost.",
   en:{nota:"Variable education credits",via:"Google for Education",time:"Annual",
       desc:"Credits for Google Cloud Platform: Compute Engine, Cloud Storage, BigQuery, Cloud Run, Kubernetes Engine, Cloud Functions and AI APIs like Vertex AI or Vision API. Ideal for machine learning projects, large-scale data analysis or learning cloud-native architectures. Access to Qwiklabs for hands-on labs and Google Cloud Skills Boost."}},

  {name:"Microsoft Azure",price:"Saldo gratuito",cat:"cloud",util:"Alta",via:"Azure Dev Tools",time:"Anual",nota:"$100 créditos + herramientas",url:"https://azure.microsoft.com/es-es/free/students/",logo:"azure.microsoft.com",
   desc:"$100 en créditos de Azure sin tarjeta de crédito, más acceso a más de 25 servicios siempre gratuitos. Incluye máquinas virtuales, Azure App Service, Azure Functions, Cognitive Services (IA), Azure DevOps, GitHub Actions integrado y acceso a software de desarrollo a través de Azure Dev Tools for Teaching. Ideal para proyectos .NET, aplicaciones empresariales y aprender arquitecturas Microsoft.",
   en:{nota:"$100 credits + tools",via:"Azure Dev Tools",time:"Annual",
       desc:"$100 in Azure credits without a credit card, plus access to over 25 always-free services. Includes virtual machines, Azure App Service, Azure Functions, Cognitive Services (AI), Azure DevOps, integrated GitHub Actions and access to development software through Azure Dev Tools for Teaching. Ideal for .NET projects, enterprise applications and learning Microsoft architectures."}},

  {name:"Oracle Cloud Free Tier",price:"Gratis",cat:"cloud",util:"Alta",via:"Oracle directo",time:"Permanente",nota:"Always free, VMs ARM gratuitas",url:"https://www.oracle.com/es/cloud/free/",logo:"oracle.com",
   desc:"Capa gratuita permanente de Oracle Cloud: 2 VMs AMD (1 OCPU, 1 GB RAM cada una) o hasta 4 VMs ARM Ampere A1 con 24 GB RAM en total. Además incluye 20 GB de almacenamiento en bloque, bases de datos autónomas, balanceador de carga, VPN y 10 TB de transferencia mensual. Las VMs ARM son especialmente potentes para inferencia de modelos de IA y servicios siempre activos sin coste.",
   en:{nota:"Always free, free ARM VMs",via:"Oracle direct",time:"Permanent",
       desc:"Oracle Cloud's permanent free tier: 2 AMD VMs (1 OCPU, 1 GB RAM each) or up to 4 ARM Ampere A1 VMs with 24 GB RAM total. Also includes 20 GB block storage, autonomous databases, load balancer, VPN and 10 TB monthly transfer. ARM VMs are especially powerful for AI model inference and always-on services at no cost."}},

  {name:"Vercel Hobby",price:"Gratis",cat:"cloud",util:"Alta",via:"Vercel directo",time:"Permanente",nota:"Hosting Next.js gratis (plan Hobby)",url:"https://vercel.com/docs/plans/hobby",logo:"vercel.com",
   desc:"Plataforma de despliegue optimizada para Next.js, React, Vue, Svelte y otros frameworks frontend. El plan Hobby gratuito (para uso no comercial) incluye previews automáticos por rama, dominio personalizado, funciones serverless edge, analytics, integración con GitHub/GitLab y zero-config deployments. Vercel no dispone de un programa Student oficial; el plan Hobby es lo que usan los estudiantes.",
   en:{nota:"Free Next.js hosting (Hobby plan)",via:"Vercel direct",time:"Permanent",
       desc:"Deployment platform optimized for Next.js, React, Vue, Svelte and other frontend frameworks. The free Hobby plan (for non-commercial use) includes automatic branch previews, custom domain, edge serverless functions, analytics, GitHub/GitLab integration and zero-config deployments. Vercel has no official Student program; the Hobby plan is what students use."}},

  {name:"MongoDB Atlas",price:"Saldo gratuito",cat:"cloud",util:"Alta",via:"GitHub Student Pack",time:"Mientras estudias",nota:"BaaS MongoDB gestionado",url:"https://www.mongodb.com/students",logo:"mongodb.com",
   desc:"Base de datos NoSQL MongoDB como servicio en la nube. Incluye cluster gratuito de 512 MB y créditos adicionales. Ofrece búsqueda full-text con Atlas Search, Atlas Vector Search para IA, Charts para visualización, Data API REST, Triggers para eventos, App Services para móvil y sincronización en tiempo real. Ideal para proyectos con esquema flexible, catálogos, perfiles de usuario o datos de sensores.",
   en:{nota:"Managed MongoDB BaaS",via:"GitHub Student Pack",time:"While studying",
       desc:"MongoDB NoSQL database as a cloud service. Includes a free 512 MB cluster and additional credits. Offers full-text search with Atlas Search, Atlas Vector Search for AI, Charts for visualization, REST Data API, Triggers for events, App Services for mobile and real-time sync. Ideal for projects with flexible schemas, catalogs, user profiles or sensor data."}},

  {name:"Heroku",price:"Saldo gratuito",cat:"cloud",util:"Media",via:"GitHub Student Pack",time:"Mientras estudias",nota:"Plataforma de despliegue PaaS",url:"https://www.heroku.com/github-students/",logo:"heroku.com",
   desc:"Plataforma como servicio (PaaS) para desplegar aplicaciones web sin gestionar servidores. Soporta Node.js, Python, Ruby, Java, PHP, Go y Scala. Incluye add-ons de bases de datos (PostgreSQL, Redis), despliegue desde Git, pipelines CI/CD, review apps automáticas y escalado sencillo. Ideal para prototipos, proyectos de clase y aplicaciones con bajo tráfico que necesiten estar online rápidamente.",
   en:{nota:"PaaS deployment platform",via:"GitHub Student Pack",time:"While studying",
       desc:"Platform as a Service (PaaS) for deploying web applications without managing servers. Supports Node.js, Python, Ruby, Java, PHP, Go and Scala. Includes database add-ons (PostgreSQL, Redis), Git deployment, CI/CD pipelines, automatic review apps and simple scaling. Ideal for prototypes, class projects and low-traffic apps that need to go online quickly."}},

  {name:"Netlify enhanced",price:"Gratis",cat:"cloud",util:"Media",via:"GitHub Student Pack",time:"Mientras estudias",nota:"Hosting estático/JAMstack",url:"https://www.netlify.com/github-students/",logo:"netlify.com",
   desc:"Plataforma de hosting para sitios estáticos y aplicaciones JAMstack. Despliegue automático desde GitHub con CDN global, previews por pull request, formularios integrados sin backend, funciones serverless, autenticación con Netlify Identity y redirects/rewrites configurables. Compatible con Gatsby, Hugo, Astro, Nuxt y cualquier generador de sitios estáticos. Sin servidor que mantener.",
   en:{nota:"Static/JAMstack hosting",via:"GitHub Student Pack",time:"While studying",
       desc:"Hosting platform for static sites and JAMstack applications. Automatic deployment from GitHub with global CDN, pull request previews, integrated forms without a backend, serverless functions, authentication with Netlify Identity and configurable redirects/rewrites. Compatible with Gatsby, Hugo, Astro, Nuxt and any static site generator. No server to maintain."}},

  {name:"Namecheap dominio + SSL",price:"Gratis",cat:"domain",util:"Alta",via:"GitHub Student Pack",time:"1 año",nota:"Dominio .me gratis + HTTPS",url:"https://nc.me/",logo:"namecheap.com",
   desc:"Dominio .me gratuito durante un año para estudiantes a través de nc.me. Incluye WHOIS privacy protection (protección de datos del registrante), gestión DNS con registros A, CNAME, MX, TXT y subdominio incluidos. Ideal para portfolio personal, proyecto TFG o marca personal. Renovación con coste pasado el primer año. Compatible con Cloudflare para CDN gratuita.",
   en:{name:"Namecheap domain + SSL",nota:"Free .me domain + HTTPS",via:"GitHub Student Pack",time:"1 year",
       desc:"Free .me domain for one year for students through nc.me. Includes WHOIS privacy protection, DNS management with A, CNAME, MX, TXT records and subdomain included. Ideal for personal portfolio, final project or personal brand. Renewal at cost after the first year. Compatible with Cloudflare for free CDN."}},

  {name:"SSL gratuito",price:"Gratis",cat:"domain",util:"Alta",via:"GitHub Student Pack",time:"1 año",nota:"Via Namecheap / Let's Encrypt",url:"https://education.github.com/pack",logo:"letsencrypt.org",
   desc:"Certificado SSL/TLS gratuito para habilitar HTTPS en tu dominio. Incluido con Namecheap en el GitHub Student Pack o gestionable automáticamente con Let's Encrypt (certbot) en cualquier servidor. Esencial para SEO, confianza del usuario y requisito de navegadores modernos. Let's Encrypt emite certificados de 90 días con renovación automática configurable vía cron.",
   en:{name:"Free SSL",nota:"Via Namecheap / Let's Encrypt",via:"GitHub Student Pack",time:"1 year",
       desc:"Free SSL/TLS certificate to enable HTTPS on your domain. Included with Namecheap in the GitHub Student Pack or automatically manageable with Let's Encrypt (certbot) on any server. Essential for SEO, user trust and required by modern browsers. Let's Encrypt issues 90-day certificates with automatic renewal configurable via cron."}},

  {name:"Cloudflare Pro",price:"Gratis",cat:"domain",util:"Alta",via:"GitHub Student Pack",time:"Mientras estudias",nota:"CDN + seguridad + DNS avanzado",url:"https://www.cloudflare.com/students/",logo:"cloudflare.com",
   desc:"Plan Pro de Cloudflare con CDN global en más de 300 ciudades, protección DDoS avanzada, firewall de aplicaciones web (WAF), optimización de imágenes (Polish), minificación automática, HTTP/3, SSL automático y analytics de tráfico. El plan Pro añade reglas de firewall avanzadas, page rules ilimitadas y soporte prioritario. Ideal para cualquier proyecto web que necesite velocidad y seguridad.",
   en:{nota:"CDN + security + advanced DNS",via:"GitHub Student Pack",time:"While studying",
       desc:"Cloudflare Pro plan with global CDN in over 300 cities, advanced DDoS protection, web application firewall (WAF), image optimization (Polish), automatic minification, HTTP/3, automatic SSL and traffic analytics. The Pro plan adds advanced firewall rules, unlimited page rules and priority support. Ideal for any web project that needs speed and security."}},

  {name:"Figma Education",price:"Gratis",cat:"design",util:"Alta",via:"Figma directo",time:"Mientras estudias",nota:"Plan completo para UI/UX design",url:"https://www.figma.com/education/",logo:"figma.com",
   desc:"Herramienta de diseño de interfaces y prototipado colaborativo en tiempo real. Plan Education incluye proyectos ilimitados, equipos ilimitados, historial de versiones completo, bibliotecas de componentes compartidas, plugins de la comunidad y FigJam para diagramas y brainstorming. Estándar de la industria para diseño UI/UX, sistemas de diseño, wireframing y entrega de especificaciones a desarrollo.",
   en:{nota:"Full plan for UI/UX design",via:"Figma direct",time:"While studying",
       desc:"Interface design and real-time collaborative prototyping tool. Education plan includes unlimited projects, unlimited teams, full version history, shared component libraries, community plugins and FigJam for diagrams and brainstorming. Industry standard for UI/UX design, design systems, wireframing and developer handoff."}},

  {name:"Canva for Education",price:"Gratis",cat:"design",util:"Media",via:"Canva directo",time:"Mientras estudias",nota:"Diseño gráfico online accesible",url:"https://www.canva.com/education/",logo:"canva.com",
   desc:"Plataforma de diseño gráfico online con miles de plantillas para presentaciones, posters, infografías, redes sociales, currículums y documentos. Plan Education incluye acceso Premium con elementos y fondos ilimitados, eliminación de fondo en imágenes, generación de imágenes con IA, carpetas compartidas y Brand Kit. Muy accesible para personas sin formación en diseño.",
   en:{nota:"Accessible online graphic design",via:"Canva direct",time:"While studying",
       desc:"Online graphic design platform with thousands of templates for presentations, posters, infographics, social media, resumes and documents. Education plan includes Premium access with unlimited elements and backgrounds, background removal, AI image generation, shared folders and Brand Kit. Very accessible for people without design training."}},

  {name:"Autodesk Education",price:"Gratis",cat:"design",util:"Media",via:"Autodesk directo",time:"1 año renovable",nota:"AutoCAD, Fusion 360, Maya…",url:"https://www.autodesk.com/education/edu-software/overview",logo:"autodesk.com",
   desc:"Licencias gratuitas para toda la suite de Autodesk: AutoCAD (dibujo técnico 2D/3D), Fusion 360 (CAD/CAM/CAE para ingeniería), Maya (animación 3D y VFX), 3ds Max (visualización arquitectónica), Revit (BIM), Inventor, Civil 3D y más. Software estándar en arquitectura, ingeniería mecánica, diseño industrial, animación y cine. Requiere verificación como estudiante o docente.",
   en:{nota:"AutoCAD, Fusion 360, Maya…",via:"Autodesk direct",time:"1 year renewable",
       desc:"Free licenses for the entire Autodesk suite: AutoCAD (2D/3D technical drawing), Fusion 360 (CAD/CAM/CAE for engineering), Maya (3D animation and VFX), 3ds Max (architectural visualization), Revit (BIM), Inventor, Civil 3D and more. Standard software in architecture, mechanical engineering, industrial design, animation and film. Requires student or teacher verification."}},

  {name:"Blender",price:"Gratis",cat:"design",util:"Media",via:"Gratuito siempre",time:"Permanente",nota:"3D open source, siempre gratis",url:"https://www.blender.org/download/",logo:"blender.org",
   desc:"Suite completa de creación 3D open source: modelado, escultura, rigging, animación, simulaciones de física y tela, renderizado (Cycles y EEVEE), composición, edición de vídeo y scripting con Python. Usado en cortometrajes, videojuegos, visualización de producto y arquitectura. Completamente gratuito sin restricciones de uso comercial. Gran comunidad y ecosistema de addons.",
   en:{nota:"Open source 3D, always free",via:"Always free",time:"Permanent",
       desc:"Complete open source 3D creation suite: modeling, sculpting, rigging, animation, physics and cloth simulations, rendering (Cycles and EEVEE), compositing, video editing and Python scripting. Used in short films, video games, product visualization and architecture. Completely free with no commercial use restrictions. Large community and addon ecosystem."}},

  {name:"Sketch",price:"Descuento",cat:"design",util:"Baja",via:"Sketch directo",time:"Anual",nota:"50% off, solo macOS",url:"https://www.sketch.com/store/education/",logo:"sketch.com",
   desc:"Herramienta de diseño vectorial para macOS enfocada en UI/UX. Precursora del diseño de interfaces moderno. Incluye componentes reutilizables, prototipos navegables, exportación precisa para desarrolladores e integración con herramientas de handoff. Aunque Figma lo ha superado en adopción por ser multiplataforma, sigue siendo popular en equipos iOS y macOS. 50% de descuento con verificación estudiantil.",
   en:{nota:"50% off, macOS only",via:"Sketch direct",time:"Annual",
       desc:"Vector design tool for macOS focused on UI/UX. Pioneer of modern interface design. Includes reusable components, navigable prototypes, precise developer export and integration with handoff tools. Although Figma has surpassed it in adoption for being cross-platform, it remains popular in iOS and macOS teams. 50% discount with student verification."}},

  {name:"Notion Education",price:"Gratis",cat:"tools",util:"Alta",via:"Notion directo",time:"Mientras estudias",nota:"Plan Plus gratuito completo",url:"https://www.notion.so/product/notion-for-education",logo:"notion.so",
   desc:"Espacio de trabajo todo en uno: notas, bases de datos, wikis, gestión de proyectos, calendario y documentos colaborativos. Plan Plus gratuito para estudiantes con bloques ilimitados, historial de páginas, invitados ilimitados y acceso a la API. Ideal para organizar apuntes, gestionar el TFG, crear wikis de proyectos, hacer seguimiento de tareas y documentar procesos. Soporte de markdown y fórmulas.",
   en:{nota:"Full free Plus plan",via:"Notion direct",time:"While studying",
       desc:"All-in-one workspace: notes, databases, wikis, project management, calendar and collaborative documents. Free Plus plan for students with unlimited blocks, page history, unlimited guests and API access. Ideal for organizing notes, managing your thesis, creating project wikis, tracking tasks and documenting processes. Markdown and formula support."}},

  {name:"Microsoft 365 Education",price:"Gratis",cat:"tools",util:"Alta",via:"Universidad",time:"Mientras estudias",nota:"Word, Excel, Teams, OneDrive",url:"https://www.microsoft.com/es-es/education/products/office",logo:"microsoft.com",
   desc:"Suite completa de Microsoft con Word, Excel, PowerPoint, OneNote, Outlook, Teams y OneDrive (1 TB). Versiones web y de escritorio. Teams para videoconferencias, chats y colaboración en documentos en tiempo real. SharePoint para intranets. OneDrive para sincronización y copias de seguridad. Accesible con el correo institucional universitario en la mayoría de universidades españolas.",
   en:{nota:"Word, Excel, Teams, OneDrive",via:"University",time:"While studying",
       desc:"Full Microsoft suite with Word, Excel, PowerPoint, OneNote, Outlook, Teams and OneDrive (1 TB). Web and desktop versions. Teams for video conferencing, chats and real-time document collaboration. SharePoint for intranets. OneDrive for sync and backups. Accessible with your university institutional email at most Spanish universities."}},

  {name:"Perplexity Pro Student",price:"Descuento",cat:"tools",util:"Alta",via:"Perplexity directo",time:"Anual",nota:"IA de búsqueda avanzada",url:"https://www.perplexity.ai/backtoschool",logo:"perplexity.ai",
   desc:"Motor de búsqueda con IA que responde preguntas con fuentes citadas en tiempo real. Plan Pro incluye acceso a GPT-4, Claude y otros modelos premium, búsquedas ilimitadas, subida de archivos para análisis, búsqueda en páginas específicas y en documentos PDF. Ideal para investigación académica, resumen de papers, búsqueda de información técnica actualizada y análisis de documentos.",
   en:{nota:"Advanced AI search",via:"Perplexity direct",time:"Annual",
       desc:"AI-powered search engine that answers questions with cited sources in real time. Pro plan includes access to GPT-4, Claude and other premium models, unlimited searches, file uploads for analysis, search within specific pages and PDF documents. Ideal for academic research, paper summarization, up-to-date technical information search and document analysis."}},

  {name:"Kaggle compute",price:"Gratis",cat:"tools",util:"Alta",via:"Kaggle directo",time:"Permanente",nota:"GPUs gratis para ML/Data Science",url:"https://www.kaggle.com",logo:"kaggle.com",
   desc:"Plataforma de ciencia de datos con notebooks en la nube con acceso gratuito a GPU (NVIDIA T4, P100) y TPU. Datasets públicos de todo tipo, competiciones con premios reales, cursos gratuitos de Python, ML, SQL y deep learning. Entorno Jupyter preconfigurado con TensorFlow, PyTorch, scikit-learn y pandas. Comunidad activa y soluciones de competiciones anteriores como referencia de aprendizaje.",
   en:{name:"Kaggle Compute",nota:"Free GPUs for ML/Data Science",via:"Kaggle direct",time:"Permanent",
       desc:"Data science platform with cloud notebooks offering free access to GPU (NVIDIA T4, P100) and TPU. Public datasets of all types, competitions with real prizes, free courses on Python, ML, SQL and deep learning. Jupyter environment pre-configured with TensorFlow, PyTorch, scikit-learn and pandas. Active community and past competition solutions as learning reference."}},

  {name:"Airtable Education",price:"Gratis",cat:"tools",util:"Media",via:"Airtable directo",time:"Mientras estudias",nota:"Base de datos visual colaborativa",url:"https://airtable.com/lp/education",logo:"airtable.com",
   desc:"Base de datos relacional con interfaz visual tipo hoja de cálculo. Permite crear vistas de tabla, kanban, calendario, galería y formularios sobre los mismos datos. Automatizaciones sin código, integraciones con Slack, Google Drive, Zapier y API REST. Ideal para gestión de proyectos grupales, seguimiento de tareas, catálogos de contenido, CRM ligero y coordinación de eventos universitarios.",
   en:{nota:"Visual collaborative database",via:"Airtable direct",time:"While studying",
       desc:"Relational database with a visual spreadsheet-like interface. Allows creating table, kanban, calendar, gallery and form views over the same data. No-code automations, integrations with Slack, Google Drive, Zapier and REST API. Ideal for group project management, task tracking, content catalogs, lightweight CRM and university event coordination."}},

  {name:"Red Hat Developer",price:"Gratis",cat:"tools",util:"Media",via:"Red Hat directo",time:"1 año renovable",nota:"RHEL + OpenShift para devs",url:"https://developers.redhat.com/articles/red-hat-developer-program-benefits",logo:"redhat.com",
   desc:"Suscripción de desarrollador gratuita que incluye Red Hat Enterprise Linux (RHEL) para hasta 16 sistemas, acceso a OpenShift (Kubernetes empresarial), Ansible Automation Platform, JBoss EAP, Quarkus y toda la documentación técnica oficial. Ideal para aprender Linux empresarial, contenedores, orquestación y automatización de infraestructura. Certificaciones RHCSA y RHCE muy valoradas en el sector.",
   en:{nota:"RHEL + OpenShift for devs",via:"Red Hat direct",time:"1 year renewable",
       desc:"Free developer subscription including Red Hat Enterprise Linux (RHEL) for up to 16 systems, access to OpenShift (enterprise Kubernetes), Ansible Automation Platform, JBoss EAP, Quarkus and all official technical documentation. Ideal for learning enterprise Linux, containers, orchestration and infrastructure automation. RHCSA and RHCE certifications highly valued in the industry."}},

  {name:"UNiDAYS",price:"Descuento",cat:"tools",util:"Media",via:"UNiDAYS directo",time:"Mientras estudias",nota:"Plataforma de descuentos variados",url:"https://www.myunidays.com/",logo:"myunidays.com",
   desc:"Plataforma de descuentos exclusivos para estudiantes universitarios verificados. Cubre tecnología (Apple, Samsung, Dell, HP, Microsoft), software, moda, comida, viajes, gimnasios y entretenimiento. Descuentos en Adobe Creative Cloud, Headspace, Gymshark, ASOS, Nike, Booking y muchos más. Verificación gratuita con correo universitario. Disponible como app móvil.",
   en:{nota:"Varied discounts platform",via:"UNiDAYS direct",time:"While studying",
       desc:"Exclusive discount platform for verified university students. Covers technology (Apple, Samsung, Dell, HP, Microsoft), software, fashion, food, travel, gyms and entertainment. Discounts on Adobe Creative Cloud, Headspace, Gymshark, ASOS, Nike, Booking and many more. Free verification with university email. Available as a mobile app."}},

  {name:"Student Beans",price:"Descuento",cat:"tools",util:"Media",via:"Student Beans",time:"Mientras estudias",nota:"Descuentos en marcas y tech",url:"https://www.studentbeans.com/es",logo:"studentbeans.com",
   desc:"Alternativa a UNiDAYS con descuentos para estudiantes en tecnología, moda, viajes, alimentación y ocio. Marcas como Lenovo, ASUS, Spotify, Sky, HelloFresh y Domino's. Se verifica con correo universitario o documentación académica. App disponible para iOS y Android. Algunos descuentos son exclusivos y no aparecen en UNiDAYS, por lo que conviene tener ambas.",
   en:{nota:"Brand and tech discounts",via:"Student Beans",time:"While studying",
       desc:"Alternative to UNiDAYS with student discounts on technology, fashion, travel, food and leisure. Brands like Lenovo, ASUS, Spotify, Sky, HelloFresh and Domino's. Verified with university email or academic documentation. App available for iOS and Android. Some discounts are exclusive and don't appear on UNiDAYS, so it's worth having both."}},

  {name:"Apple Education pricing",price:"Descuento",cat:"tools",util:"Media",via:"Apple directo",time:"Por compra",nota:"Mac/iPad a precio reducido",url:"https://www.apple.com/es-edu/store",logo:"apple.com",
   desc:"Precios especiales en Mac, iPad, accesorios y AppleCare para estudiantes y docentes. Descuentos de entre el 5% y el 15% según el producto. MacBook Air y MacBook Pro son los más comprados. En septiembre suele haber promoción adicional con AirPods gratuitos al comprar Mac o iPad. También descuento en suscripciones Apple One y Apple Music Student. Compra en la Apple Education Store online.",
   en:{name:"Apple Education Pricing",nota:"Mac/iPad at reduced price",via:"Apple direct",time:"Per purchase",
       desc:"Special prices on Mac, iPad, accessories and AppleCare for students and teachers. Discounts between 5% and 15% depending on the product. MacBook Air and MacBook Pro are the most purchased. In September there is usually an additional promotion with free AirPods when buying a Mac or iPad. Also discounts on Apple One and Apple Music Student subscriptions. Buy at the Apple Education Store online."}},

  {name:"Spotify Student",price:"Descuento",cat:"media",util:"Alta",via:"Spotify directo",time:"Anual renovable",nota:"~50% descuento en Premium",url:"https://www.spotify.com/es/student/",logo:"spotify.com",
   desc:"Plan Premium de Spotify a precio reducido (~4,99€/mes en España, casi un 50% de descuento). Música sin anuncios, descarga para escuchar sin conexión, calidad de audio alta, escucha en cualquier dispositivo y sin límite de saltos. Verificación mediante SheerID con correo universitario. Renovable cada 12 meses mientras se sea estudiante. Incluye Hulu en EEUU pero no en España.",
   en:{nota:"~50% off Premium",via:"Spotify direct",time:"Annual renewable",
       desc:"Spotify Premium at a reduced price (~€4.99/month in Spain, almost 50% off). Ad-free music, offline downloads, high audio quality, listening on any device and no skip limit. Verification via SheerID with university email. Renewable every 12 months while you are a student. Includes Hulu in the US but not in Spain."}},

  {name:"Amazon Prime Student",price:"Descuento",cat:"media",util:"Media",via:"Amazon directo",time:"Anual",nota:"6 meses gratis, luego descuento",url:"https://www.amazon.es/prime/student",logo:"amazon.es",
   desc:"6 meses de Amazon Prime gratis y luego precio reducido (~4,49€/mes o ~24€/año). Incluye envíos rápidos gratuitos, Prime Video, Prime Music, Prime Reading (e-books), Amazon Photos con almacenamiento ilimitado, Prime Gaming con juegos y contenido gratis cada mes. Verificación con correo universitario. Especialmente útil durante el periodo gratuito para material de estudio y entregas de proyectos.",
   en:{nota:"6 months free, then discount",via:"Amazon direct",time:"Annual",
       desc:"6 months of Amazon Prime free and then a reduced price (~€4.49/month or ~€24/year). Includes free fast shipping, Prime Video, Prime Music, Prime Reading (e-books), Amazon Photos with unlimited storage, Prime Gaming with free games and content every month. Verification with university email. Especially useful during the free period for study materials and project deliveries."}},

  {name:"YouTube Premium Student",price:"Descuento",cat:"media",util:"Media",via:"Google directo",time:"Anual renovable",nota:"Sin anuncios + YouTube Music",url:"https://www.youtube.com/premium/student",logo:"youtube.com",
   desc:"YouTube sin anuncios, reproducción en segundo plano (ideal para podcasts y música mientras estudias), descargas offline y YouTube Music incluido. Precio reducido para estudiantes (~4,49€/mes). Verificación mediante SheerID. Muy útil para consumir contenido educativo sin interrupciones: tutoriales de programación, conferencias, documentales y canales técnicos. Disponible en iOS, Android y web.",
   en:{nota:"Ad-free + YouTube Music",via:"Google direct",time:"Annual renewable",
       desc:"YouTube without ads, background playback (ideal for podcasts and music while studying), offline downloads and YouTube Music included. Reduced price for students (~€4.49/month). Verification via SheerID. Very useful for consuming educational content without interruptions: programming tutorials, conferences, documentaries and technical channels. Available on iOS, Android and web."}},

  {name:"Apple Music Student",price:"Descuento",cat:"media",util:"Media",via:"Apple directo",time:"Anual renovable",nota:"Precio reducido en streaming",url:"https://www.apple.com/es/apple-music/",logo:"apple.com",
   desc:"Apple Music con catálogo de más de 100 millones de canciones, audio espacial con Dolby Atmos, letras sincronizadas, radio Apple Music 1, listas de reproducción editoriales y descarga para escuchar sin conexión. Precio estudiante ~5,99€/mes. Integración nativa con dispositivos Apple. Si ya usas iPhone/Mac, es la opción más integrada. Verificación anual con SheerID mediante correo universitario.",
   en:{nota:"Reduced price streaming",via:"Apple direct",time:"Annual renewable",
       desc:"Apple Music with a catalog of over 100 million songs, spatial audio with Dolby Atmos, synchronized lyrics, Apple Music 1 radio, editorial playlists and offline downloads. Student price ~€5.99/month. Native integration with Apple devices. If you already use iPhone/Mac, it's the most integrated option. Annual verification via SheerID with university email."}},
];

const PRICE_ICON = {
  Gratis:           `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M6 1v10M3.5 3.5C3.5 2.67 4.62 2 6 2s2.5.67 2.5 1.5S7.38 5 6 5s-2.5.67-2.5 1.5S4.62 8 6 8s2.5.67 2.5 1.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="square"/></svg>`,
  Descuento:        `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M9 3 3 9M3.5 3.5h.01M8.5 8.5h.01" stroke="currentColor" stroke-width="1.3" stroke-linecap="square"/><circle cx="3.5" cy="3.5" r="1" fill="currentColor"/><circle cx="8.5" cy="8.5" r="1" fill="currentColor"/></svg>`,
  "Saldo gratuito": `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><rect x="1" y="3" width="10" height="7" rx="0" stroke="currentColor" stroke-width="1.2"/><path d="M1 5.5h10" stroke="currentColor" stroke-width="1.2"/></svg>`,
};

const CAT_ICON = {
  dev:    `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M3.5 4 1.5 6l2 2M8.5 4l2 2-2 2M5.5 9l1-6" stroke="currentColor" stroke-width="1.2" stroke-linecap="square" stroke-linejoin="miter"/></svg>`,
  cloud:  `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M9 8.5H3.5A2 2 0 0 1 3.5 4.5a2.5 2.5 0 0 1 5 .5H9a1.5 1.5 0 0 1 0 3Z" stroke="currentColor" stroke-width="1.2"/></svg>`,
  design: `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 10 8 2l2 2-6 6H2v-2Z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="miter"/></svg>`,
  media:  `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><circle cx="6" cy="6" r="4.5" stroke="currentColor" stroke-width="1.2"/><path d="M5 4.5v3l3-1.5-3-1.5Z" fill="currentColor"/></svg>`,
  edu:    `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M6 2 1 5l5 3 5-3-5-3Z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="miter"/><path d="M3.5 6.5V9c0 .5 1.1 1.5 2.5 1.5S8.5 9.5 8.5 9V6.5" stroke="currentColor" stroke-width="1.2"/></svg>`,
  tools:  `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M7.5 2a2.5 2.5 0 0 0-2.4 3.1L2 8.2 2 10h1.8L7 6.9A2.5 2.5 0 0 0 7.5 2Z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="miter"/></svg>`,
  domain: `<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><circle cx="6" cy="6" r="4.5" stroke="currentColor" stroke-width="1.2"/><path d="M6 1.5c-1.5 2-1.5 7 0 9M6 1.5c1.5 2 1.5 7 0 9M1.5 6h9" stroke="currentColor" stroke-width="1.2"/></svg>`,
};

const CAT_CLASS  = {dev:"tag-dev",cloud:"tag-cloud",design:"tag-design",media:"tag-media",edu:"tag-edu",tools:"tag-tools",domain:"tag-domain"};
const PRICE_CLASS = {Gratis:"tag-gratis", Descuento:"tag-descuento", "Saldo gratuito":"tag-creditos"};
const UTIL_ORDER  = {Alta:0, Media:1, Baja:2};
